sudo: required
services:
  - docker

before_install:
  - docker build -t aylayn/docker-react  -f Dockerfile.dev .

script:
  - docker run aylayn/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-641656467617"
  bucket_path: "docker-react"

  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secret: "$AWS_SECRET_KEY"